<?php require('common/head.php')?>
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">
<?php require('common/body.php')?>

<div class="aboutustop text-center">
  <div class="mainpagepadding height2">
  </div>
  <div class = "inputinfo margin10 padding20">
    <h1 class="h1">About us</h1>
  </div>
</div>
  <div class = "mainpagepadding height30">
    <br><br>
    <hr style="height:2px" color="#969494">
    <div class ="imageframe margin40 padding10 text-center">
      <br>
      <img src="images/teama.png" alt="heartchart" class="center">
      <br><br>
      <div class = "inputinfo" style="height:100px">
        <h2 class="h2" font size=20px>
          "Ella Kim, Aiden Kim, Justin Hwang, Danial Kim, James Mun"
        </h2>
        <br>
        <div class="inputinfo2 text-right" style = "float:left">
        WHO WE ARE?<br>We are a tema A for QI-IoT project in 2018 winter
        </div>
        <div class = "inputinfo3 text-left" style = "float:left">
          WHAT WE DO?<br>We made a Software for doctors to monitor their patients.
        </div>
      </div>
    </div>

    <br>
    <br>
    <br>
    <div class="padding30">
      <hr style="height:1px" color="#969494">
      Department of computer engineering, Chosun university
    </div>
  </div>
</div>
</body>



<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

</html>
