<?php require('common/head.php') ?>
<?php require('common/bodynosession.php')?>

        <div class="content" style="margin-top:-40px">
            <div class="container-fluid">
                <div class="row">
                    <div class="card">
                            <div class="row" style="margin-left: 40px;margin-top: 40px;">
                                <div class="header">
                                    <h1 class="title">AQI Data</h1>
                                </div>
                                <div>
                                    <div class="form-group">
                                        <div class="col-sm-2">
                                            <input type="date" id="fdate" class="form-control" maxlength="10">
                                        </div>
                                        <div class="col-sm-1" style="width:40px;margin-top:5px">~</div>
                                        <div class="col-sm-2">
                                            <input type="date" id="ldate" class="form-control" maxlength="10">
                                        </div>
                                        <div class="col-sm-2" style="padding-top: 4px;">
                                            <input type="button" id="rrsearch" value="search" onclick="aqidata()" maxlength="10">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="Line_Controls_Chart">
                                <!-- 라인 차트 생성할 영역 -->
                                <div id="lineChartArea" style="padding:0px 20px 0px 0px;"></div>
                                <!-- 컨트롤바를 생성할 영역 -->
                                <div id="controlsArea" style="padding:10px 20px 0px 0px;"></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

    <!--   Core JS Files   -->
    <script src="assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="assets/js/bootstrap-notify.js"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="assets/js/demo.js"></script>


    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script type="text/javascript">
        function aqidata() {
            var chartDrowFun = {

                chartDrow: function () {
                    var chartData = '';

                    //날짜형식 변경하고 싶으시면 이 부분 수정하세요.
                    var chartDateformat = 'yy-MM-dd HH:mm';
                    //라인차트의 라인 수
                    var chartLineCount = 20;
                    //컨트롤러 바 차트의 라인 수
                    var controlLineCount = 20;


                    function drawDashboard() {

                        var data = new google.visualization.DataTable();
                        //그래프에 표시할 컬럼 추가
                        data.addColumn('datetime', 'Date');
                        data.addColumn('number', 'PM2.5');
                        data.addColumn('number', 'O3');
                        data.addColumn('number', 'NO2');
                        data.addColumn('number', 'CO');
                        data.addColumn('number', 'SO2');
                        data.addColumn('number', 'Temperature');

                        //그래프에 표시할 데이터
                        var dataRow = [];

                        var date = {
                            fdate : $("#fdate").val(),
                            ldate : $("#ldate").val()
                        };

                        $.ajax({
                            type: "POST",
                            url: "/aqi",
                            data: JSON.stringify(date),

                            success: function (response) {

                                var res = JSON.parse(response);

                                if (res['status'] == true) {
                                    var arr = res['data'];
                                    var count = arr.length;

                                    for(var i = 0; i < count; i++){
                                        var ts = arr[i]['TS'].split(" ");
                                        var ymd = ts[0].split("-");
                                        var hm = ts[1].split(":");
                                        var middle = ymd[1]-1;
                                        var pm25 = arr[i]['PM2.5']; var o3 = arr[i]['O3']; var no2 = arr[i]['NO2'];
                                        var co = arr[i]['CO']; var so2 = arr[i]['SO2']; var tem = arr[i]['Temperature'];

                                        dataRow = [new Date(ymd[0], middle, ymd[2] , hm[0], hm[1]), Math.round(pm25), Math.round(o3), Math.round(no2),
                                            Math.round(co), Math.round(so2), Math.round(tem)];
                                        data.addRow(dataRow);
                                    }

                                    var chart = new google.visualization.ChartWrapper({
                                        chartType: 'LineChart',
                                        containerId: 'lineChartArea', //라인 차트 생성할 영역
                                        options: {
                                            isStacked: 'percent',
                                            focusTarget: 'category',
                                            height: 500,
                                            width: '100%',
                                            legend: {position: "top", textStyle: {fontSize: 13}},
                                            pointSize: 5,
                                            tooltip: {textStyle: {fontSize: 12}, showColorCode: true, trigger: 'both'},
                                            hAxis: {
                                                format: chartDateformat, gridlines: {
                                                    count: chartLineCount, units: {
                                                        years: {format: ['yyyy']},
                                                        months: {format: ['MM']},
                                                        days: {format: ['dd']},
                                                        hours: {format: ['HH']}
                                                    }
                                                }, textStyle: {fontSize: 12}
                                            },
                                            vAxis: {
                                                minValue: 200,
                                                viewWindow: {min: 0},
                                                gridlines: {count: -1},
                                                textStyle: {fontSize: 12}
                                            },
                                            animation: {startup: true, duration: 500, easing: 'in'},
                                            annotations: {
                                                pattern: chartDateformat,
                                                textStyle: {
                                                    fontSize: 15,
                                                    bold: true,
                                                    italic: true,
                                                    color: '#871b47',
                                                    auraColor: '#d799ae',
                                                    opacity: 0.8,
                                                    pattern: chartDateformat
                                                }
                                            },
                                            vAxes: {
                                                // Adds titles to each axis.
                                                0: {title: 'AQI'}
                                            },
                                            hAxes: {
                                                0: {title: 'Date'}
                                            }
                                        }
                                    });

                                    var control = new google.visualization.ControlWrapper({
                                        controlType: 'ChartRangeFilter',
                                        containerId: 'controlsArea',  //control bar를 생성할 영역
                                        options: {
                                            ui: {
                                                chartType: 'LineChart',
                                                chartOptions: {
                                                    chartArea: {'width': '95%', 'height': 80},
                                                    hAxis: {
                                                        'baselineColor': 'none', format: chartDateformat, textStyle: {fontSize: 12},
                                                        gridlines: {
                                                            count: controlLineCount, units: {
                                                                years: {format: ['yyyy']},
                                                                months: {format: ['MM']},
                                                                days: {format: ['dd']},
                                                                hours: {format: ['HH']}
                                                            }
                                                        }
                                                    }
                                                }
                                            },
                                            filterColumnIndex: 0
                                        }
                                    });

                                    var date_formatter = new google.visualization.DateFormat({pattern: chartDateformat});
                                    date_formatter.format(data, 0);

                                    var dashboard = new google.visualization.Dashboard(document.getElementById('Line_Controls_Chart'));
                                    window.addEventListener('resize', function () {
                                        dashboard.draw(data);
                                    }, false); //화면 크기에 따라 그래프 크기 변경
                                    dashboard.bind([control], [chart]);
                                    dashboard.draw(data);

                                }
                                else
                                    alert(res['message']);
                            }
                        });

                    }

                    google.charts.setOnLoadCallback(drawDashboard);

                }
            }
            $(document).ready(function () {
                google.charts.load('current', {'packages': ['line', 'controls']});
                chartDrowFun.chartDrow(); //chartDrow() 실행
            });
        }
    </script>

</html>