<?php require('common/head.php')?>
<?php require('common/body.php')?>

        <div class="content">
            <div class="container-fluid">
                <div class="col-md-4">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Change Password</h4>
                        </div>
                        <div class="content">
                            <form id="changepwd-form" method="post" class="form-group">
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>New Password</label>
                                            <input type="password" id="changenpwd" class="form-control" placeholder="New Password" pattern="[A-Za-z0-9]{6,10}" maxlength="10" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Confirm Password</label>
                                            <input type="password" id="changecpwd" class="form-control" placeholder="Confirm Password" pattern="[A-Za-z0-9]{6,10}" maxlength="10" required>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-info btn-fill pull-left">SUBMIT</button>
                                <div class="clearfix"></div>

                                <script type="text/javascript">
                                    $("#changepwd-form").submit(function(){

                                        var pd1 = $("#changenpwd").val();
                                        var pd2 = $("#changecpwd").val();
                                        var charcount = 0;

                                        for(var i = 0; i < pd1.length; i++) {
                                            if(pd1[i]>="A" && pd1[i]<='z') {
                                                charcount++;
                                            }
                                        }

                                        if(charcount<2) {
                                            alert("You must contain two characters at least");
                                            return false;
                                        }

                                        if(pd1!=pd2) {
                                            alert("Password is wrong");
                                            return false;
                                        }

                                        var data = {
                                            pwd : pd1
                                        };

                                        $.ajax({
                                            type: "POST",
                                            url: "/changepwd",
                                            data: JSON.stringify(data),
                                            success: function (response) {

                                                var res = JSON.parse(response);

                                                if (res['status'] == true) {
                                                    alert("Password change is successful");
                                                    window.location = '/';
                                                }
                                                else
                                                    alert(res['message']);
                                            }
                                        });

                                        return false;

                                    });
                                </script>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- jQuery 3 -->
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Select2 -->
<script src="bower_components/select2/dist/js/select2.full.min.js"></script>
<!-- InputMask -->
<script src="plugins/input-mask/jquery.inputmask.js"></script>
<script src="plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="plugins/input-mask/jquery.inputmask.extensions.js"></script>
<!-- date-range-picker -->
<script src="bower_components/moment/min/moment.min.js"></script>
<script src="bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- bootstrap datepicker -->
<script src="bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- bootstrap color picker -->
<script src="bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
<!-- bootstrap time picker -->
<script src="plugins/timepicker/bootstrap-timepicker.min.js"></script>
<!-- SlimScroll -->
<script src="bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- iCheck 1.0.1 -->
<script src="plugins/iCheck/icheck.min.js"></script>
<!-- FastClick -->
<script src="bower_components/fastclick/lib/fastclick.js"></script>

<script>
    $(function () {
        //Date picker
        $('#datepicker').datepicker({
            autoclose: true
        })
    })
</script>


</body>

    <!--   Core JS Files   -->
    <script src="assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="assets/js/demo.js"></script>

</html>
