<?php require('common/head.php')?>
<?php require('common/body.php')?>

<div class="mainpagetop text-right">
  <div class="mainpagepadding height10">
  </div>
  <div class = "inputinfo margin10 padding20">
    <h1 class="h1">You can be more convenient by using&nbsp&nbsp<br>Mydoctor A&nbsp&nbsp</h1>
    <br>
    <p class = "first">This page is only for doctors&nbsp&nbsp&nbsp&nbsp&nbsp</p>
  </div>
</div>
  <div class = "mainpagepadding height30">
    <br><br>
    <hr style="height:2px" color="#969494">
    <div class ="inputinfo margin40 padding10 text-center">
      <h2 class = "h2">
        Medical Software for Clinics and Hospitals
      </h2>
      <br><br>
      <div class = "inputinfo" style="height:120px">
        <div class="inputinfo2 text-right" style = "float:left">
          INCLUDES EVERYTHING YOU NEED<br>CONNECTS ALL YOUR PATIENTS<br>EASY TO MONITOR THEIR HEALTH
        </div>
        <div class = "inputinfo3 text-left" style = "float:left">
          Start the Mydoctor A.<br>If you connect with your patient,<br>
          you can monitor their heart-related<br> and atmospheric information like below.
        </div>
      </div>
    </div>
    <br><br><br><br>
    <div class="imgframe">
      <img src="images/heart_chart.png" alt="heartchart" class="center">
      <br><br>
      <img src="images/aqi_chart.png" alt="aqichart" class="center">
    </div>
    <br>
    <br>
    <br>
    <div class="padding30">
      <hr style="height:1px" color="#969494">
    </div>
  </div>
</div>
</body>



<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

</html>
