<?php session_start();?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="../assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>My Doctor A</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="assets/css/pe-icon-7-stroke.css" rel="stylesheet" />

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="bower_components/Ionicons/css/ionicons.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="plugins/iCheck/all.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="plugins/timepicker/bootstrap-timepicker.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="bower_components/select2/dist/css/select2.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.12.4.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.8.18/jquery-ui.min.js"></script>


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery.min.js"></script>

    <script src="amcharts/amcharts.js" type="text/javascript"></script>
    <script src="amcharts/serial.js" type="text/javascript"></script>

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>

</head>
<body>
<div class="wrapper">
    <div class="sidebar" data-color="gray" data-image="assets/img/walking-sidebar2.jpg">

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="/" class="simple-text">
                    My Doctor A
                </a>
            </div>

            <ul class="nav">
                <li>
                    <a href="/">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li>
                    <a href="/aboutus">
                        <i class="pe-7s-bell"></i>
                        <p>About us</p>
                    </a>
                </li>
                <li>
                    <a href="#" onclick="RealtimePatientpage()">
                        <i class="pe-7s-display1"></i>
                        <p>Real-time Patient</p>
                    </a>
                </li>
                <li>
                    <a href="#" onclick="HistoricalPatientpage()">
                        <i class="pe-7s-note2"></i>
                        <p>Historical Patient</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li id="signup" style="display:none;">
                            <a href="/chkemail">
                                <p>Sign Up</p>
                            </a>
                        </li>
                        <li id="signin" style="display:none;">
                            <a href="/signin">
                                <p>Sign In</p>
                            </a>
                        </li>

                        <li id="profile" style="display:none;">
                            <a href="/chkpwdprofile">
                                <p>Profile</p>
                            </a>
                        </li>
                        <li id="idcancellation" style="display:none;">
                            <a href="/idcancellation">
                                <p>ID Cancellation</p>
                            </a>
                        </li>
                        <li id="changepwd" style="display:none;">
                            <a href="/chkpwd">
                                <p>Change Password</p>
                            </a>
                        </li>
                        <li id="signout" style="display:none;">
                            <a href="#" onclick="signout()">
                                <p>Sign Out</p>
                            </a>
                            <script>
                                function signout() {
                                    var data = {
                                        status : "sign-out"
                                    }
                                    $.ajax({
                                        type: "POST",
                                        url: "/signout",
                                        data: JSON.stringify(data),

                                        success: function (response) {

                                            var res = JSON.parse(response);

                                            if (res['status'] == true) {
                                                window.location = '/';
                                            }
                                            else
                                                alert(res['message']);
                                        }
                                    });
                                }
                            </script>
                        </li>
                    </ul>
                    <script type="text/javascript">
                        <?php
                        if(!(isset($_SESSION['status']))) {
                            $_SESSION['status'] = "not sign-in";
                            $_SESSION['dsn'] = "zero";
                        }

                        if ($_SESSION['status'] == "not sign-in") { ?>
                        document.getElementById('signup').style.display = "block";
                        document.getElementById('signin').style.display = "block";
                        document.getElementById("profile").style.display = "none";
                        document.getElementById("idcancellation").style.display = "none";
                        document.getElementById("changepwd").style.display = "none";
                        document.getElementById("signout").style.display = "none";
                        <?php }
                        else { ?>
                        document.getElementById('signup').style.display = "none";
                        document.getElementById('signin').style.display = "none";
                        document.getElementById("profile").style.display = "block";
                        document.getElementById("idcancellation").style.display = "block";
                        document.getElementById("changepwd").style.display = "block";
                        document.getElementById('signout').style.display = "block";
                        <?php } ?>
                    </script>
                    <script>
                        function RealtimePatientpage() {
                            if("<?echo $_SESSION['status'] ?>" == "not sign-in") {
                                alert("You need to sign in");
                            }
                            else {
                                window.location="/realtime";
                            }
                        }
                        function HistoricalPatientpage() {
                            if("<?echo $_SESSION['status'] ?>" == "not sign-in") {
                                alert("You need to sign in");
                            }
                            else {
                                window.location="/historical";
                            }
                        }
                    </script>
                </div>
            </div>
        </nav>
        <div class="content" style="margin-top:-40px">
            <div class="container-fluid">
                <div class="row">
                    <div class="card">
                        <div class="row" style="margin-left: 40px;margin-top: 40px;">
                            <div class="header">
                                <h1 class="title">Historical AQI Data</h1>
                            </div>
                            <div>
                                <div class="form-group">
                                    <div class="col-sm-2">
                                        <input type="date" id="fdate" class="form-control" value="<? echo date('Y-m-d', strtotime(date('Y-m-d').'-1 days'));?>" maxlength="10">
                                    </div>
                                    <div class="col-sm-1" style="width:40px;margin-top:5px">~</div>
                                    <div class="col-sm-2">
                                        <input type="date" id="ldate" class="form-control" value="<? echo date('Y-m-d', strtotime(date('Y-m-d').'-1 days'));?>" maxlength="10">
                                    </div>
                                    <div class="col-sm-2" style="padding-top: 4px;">
                                        <input type="button" id="rrsearch" value="search" class="btn" onclick="generateChartData()">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="chartdiv" style="width: 100%; height: 500px;"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div id="map" style="height: 700px">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

    <!--   Core JS Files   -->
    <script src="assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7S-qT1aGluOMhoADF4UliHseyqtAZA_0"></script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="assets/js/demo.js"></script>


    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script src="https://maps.googleapis.com/maps/api/js"></script>

    <script>
        var arr;
        var count;
        var circles = [];
        var markers = [];
        var chartData;
        var map;
        var chart;
        var highlight;

        $().ready(function(){
            // Create a map object and specify the DOM element for display.
            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 32.8793991, lng: -117.2368268},
                zoom: 8
            });
        });
    </script>
    <script>
        function generateChartData() {
            deleteMarkers();
            chartData = [];
            var date = {
                fdate : $("#fdate").val(),
                ldate : $("#ldate").val()
            };
            $.ajax({
                type: "POST",
                url: "/aqi",
                data: JSON.stringify(date),

                success: function (response) {

                    var res = JSON.parse(response);

                    if (res['status'] == true) {
                        arr = res['data'];
                        count = arr.length;

                        for (var i = 0; i < count; i++) {
                            var ts = arr[i]['TS'].split(" ");
                            var ymd = ts[0].split("-");
                            var hm = ts[1].split(":");
                            var middle = ymd[1] - 1;
                            var pm25 = Math.round(arr[i]['PM2.5']);
                            var o3 = Math.round(arr[i]['O3']);
                            var no2 = Math.round(arr[i]['NO2']);
                            var co = Math.round(arr[i]['CO']);
                            var so2 = Math.round(arr[i]['SO2']);
                            var tem = Math.round(arr[i]['Temperature']);

                            var newDate = new Date(ymd[0], middle, ymd[2], hm[0], hm[1], hm[2]);

                            chartData.push({
                                date: newDate,
                                pm25: pm25,
                                o3: o3,
                                no2: no2,
                                co: co,
                                so2: so2,
                                tem: tem
                            });
                        }

                        chart = AmCharts.makeChart("chartdiv", {
                            type: "serial",
                            legend: {
                                equalWidths: false,
                                useGraphSettings: true,
                                valueAlign: "left",
                                valueWidth: 20
                            },
                            dataProvider: chartData,
                            dataDateFormat: "YY-MM-DD JJ:NN:SS",
                            categoryField: "date",
                            categoryAxis: {
                                minPeriod: "ss",
                                parseDates: true,
                                gridAlpha: 0.15,
                                minorGridEnabled: true,
                                axisColor: "#DADADA",
                                title: "Date"
                            },
                            valueAxes: [{
                                axisAlpha: 0.2,
                                id: "v1",
                                title: "AQI"
                            },{
                                axisAlpha: 0.2,
                                position: "right",
                                id: "v2",
                                title: "Temperature",
                                unit: " ℉"
                            }],
                            graphs: [{
                                title: "PM2.5",
                                id: "g1",
                                valueAxis: "v1",
                                valueField: "pm25",
                                bullet: "round",
                                bulletBorderColor: "#FFFFFF",
                                bulletBorderAlpha: 1,
                                lineThickness: 1,
                                lineColor: "#93DAFF",
                                negativeLineColor: "#0352b5",
                                balloonText: "[[category]]<br><b><span style='font-size:14px;'>PM2.5: [[value]]</span></b>"
                            },{
                                title: "O3",
                                id: "g2",
                                valueField: "o3",
                                bullet: "round",
                                bulletBorderColor: "#FFFFFF",
                                bulletBorderAlpha: 1,
                                lineThickness: 1,
                                lineColor: "#FFDC3C",
                                negativeLineColor: "#b5030d",
                                balloonText: "[[category]]<br><b><span style='font-size:14px;'>O3: [[value]]</span></b>"
                            },{
                                title: "NO2",
                                id: "g3",
                                valueField: "no2",
                                bullet: "round",
                                bulletBorderColor: "#FFFFFF",
                                bulletBorderAlpha: 1,
                                lineThickness: 1,
                                lineColor: "#FFB6C1",
                                negativeLineColor: "#b5030d",
                                balloonText: "[[category]]<br><b><span style='font-size:14px;'>NO2: [[value]]</span></b>"
                            },{
                                title: "CO",
                                id: "g4",
                                valueField: "co",
                                bullet: "round",
                                bulletBorderColor: "#FFFFFF",
                                bulletBorderAlpha: 1,
                                lineThickness: 1,
                                lineColor: "#3DFF92",
                                negativeLineColor: "#b5030d",
                                balloonText: "[[category]]<br><b><span style='font-size:14px;'>CO: [[value]]</span></b>"
                            },{
                                title: "SO2",
                                id: "g5",
                                valueField: "so2",
                                bullet: "round",
                                bulletBorderColor: "#FFFFFF",
                                bulletBorderAlpha: 1,
                                lineThickness: 1,
                                lineColor: "#D36EEC",
                                negativeLineColor: "#b5030d",
                                balloonText: "[[category]]<br><b><span style='font-size:14px;'>SO2: [[value]]</span></b>"
                            },{
                                title: "Temperature",
                                id: "g6",
                                valueAxis: "v2",
                                valueField: "tem",
                                bullet: "round",
                                bulletBorderColor: "#FFFFFF",
                                bulletBorderAlpha: 1,
                                lineThickness: 1,
                                lineColor: "#FF6464",
                                negativeLineColor: "#b5030d",
                                balloonText: "[[category]]<br><b><span style='font-size:14px;'>Temperature: [[value]]℉</span></b>"
                            }],
                            chartCursor: {
                                fullWidth: true,
                                categoryBalloonDateFormat: "YY-MM-DD JJ:NN",
                                valueLineBalloonEnabled: true,
                                cursorAlpha: 0.1
                            },
                            chartScrollbar: {
                                scrollbarHeight: 40,
                                color: "#FFFFFF",
                                autoGridCount: true
                            },

                            mouseWheelZoomEnabled: true
                        });

                        chart.addListener("dataUpdated", zoomChart);

                        chart.addListener("clickGraphItem", function(event) {
                            resetMarkers();
                            if (event.index === undefined)
                                return;
                            highlightMarker(chart.dataProvider[event.index].marker);
                        });

                        chart.addListener("init", function() {
                            chart.chartCursor.addListener("onHideCursor", function() {
                                resetMarkers();
                            });
                        });

                        initMap();
                        google.maps.event.addDomListener(window, 'load', initMap);
                    }
                }
            });
        }

        function zoomChart() {
            // different zoom methods can be used - zoomToIndexes, zoomToDates, zoomToCategoryValues
            chart.zoomToIndexes(chartData.length - 40, chartData.length - 1);
        }

        function initMap() {
            var mapOptions = {
                zoom : 18,
                center : new google.maps.LatLng(arr[count-1]['LAT'],arr[count-1]['LNG'])
            };

            map = new google.maps.Map(document.getElementById('map'),mapOptions);

            var points = [];
            for (var i = 0; i < chart.dataProvider.length; i++) {
                var dp = chart.dataProvider[i];
                points.push(new google.maps.LatLng(arr[i].LAT, arr[i].LNG));
                dp.marker = addMarker(points[i], i);
            }

            /*var markerCluster = new MarkerClusterer(map, markers,
                {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});*/
        }

        function addMarker(points, id) {
            var pm25 = Math.round(arr[id]['PM2.5']);
            var o3 = Math.round(arr[id]['O3']);
            var no2 = Math.round(arr[id]['NO2']);
            var co = Math.round(arr[id]['CO']);
            var so2 = Math.round(arr[id]['SO2']);
            var tem = Math.round(arr[id]['Temperature']);
            var aqiarr = [pm25, o3, no2, co, so2];

            var str = arr[id]['TS'] + " PM2.5 : " + pm25 + ", O3 : " + o3 + ", NO2 : " + no2 + ", CO : " + co + ", SO2 : " + so2 + ", Temperature : " + tem + '℉';

            for(var i=0; i<4; i++) {
                if(aqiarr[i] >= aqiarr[i+1]) {
                    aqiarr[i+1] = aqiarr[i];
                }
            }

            var max = aqiarr[4];
            var url;

            if(max >= 0 && max <= 50) {
                url = "images/cloud1.png";
            } else if(max >= 51 && max <=100) {
                url = "images/cloud2.png";
            } else if(max >= 101 && max <=150) {
                url = "images/cloud3.png";
            } else if(max >= 151 && max <=200) {
                url = "images/cloud4.png";
            } else if(max >= 201 && max <=300) {
                url = "images/cloud5.png";
            } else if(max >= 301) {
                url = "images/cloud6.png";
            }

            var marker = new google.maps.Marker({
                title: str,
                position: points,
                icon: {
                    url : url // 마커로 사용할 이미지
                },
                opacity: 0.5,
                map: map,
                draggable: false,
                id: id
            });

            var Circle = new google.maps.Circle({
                strokeColor: '#CCCCCC',
                strokeOpacity: 0.8,
                strokeWeight: 1,
                fillColor: '#FFFFFF',
                fillOpacity: 0.1,
                map: map,
                center: points,
                radius: 50
            });
            Circle.setMap(map);
            
            circles.push(Circle);
            markers.push(marker);

            var contentString = '<div id="content">'+
                '<div id="siteNotice">'+
                '</div>'+
                '<h2 id="firstHeading" class="firstHeading">AQI</h2>'+
                '<div id="bodyContent">'+
                '<p>Date : ' + arr[id]['TS'] +
                '<br>PM2.5 : ' + pm25 +
                '<br>O3 : ' + o3 +
                '<br>NO2 : ' + no2 +
                '<br>CO : ' + co +
                '<br>SO2 : ' + so2 +
                '<br>Temperature : ' + tem + '℉</p>' +
                '</div>'+
                '</div>';


            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });

            google.maps.event.addListener(marker, 'click', function() {
                infowindow.open(map,marker);
            });
            google.maps.event.addListener(marker, 'mouseover', function() {
                resetMarkers();
                maphighlightMarker(this);
                chart.chartCursor.showCursorAt(chart.chartData[this.id].category);
            });
            google.maps.event.addListener(marker, 'mouseout', function() {
                resetMarkers();
                chart.chartCursor.hideCursor();
            });

            return marker;
        }

        function highlightMarker(marker) {
            marker.setOpacity(1);
            map.panTo(marker.getPosition());
        }

        function maphighlightMarker(marker) {
            marker.setOpacity(1);
            highlight = marker;
        }

        function getMarkers() {
            return chart.dataProvider.map(function(element, index, array) {
                return element.marker;
            })
        }

        function resetMarkers() {
            var markers = getMarkers();
            for (var i = 0; i < markers.length; i++) {
                if (markers[i] !== undefined)
                    markers[i].setOpacity(0.5);
            }
        }

        function deleteMarkers() {
            for(var i=0;i<markers.length;i++) {
                markers[i].setMap(null);
                circles[i].setMap(null);
            }
            markers = [];
            circles = [];
        }
    </script>
</html>