<?php require('common/head.php') ?>
<?php require('common/bodynosession.php')?>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h1 class="title">Patient List - Real Time Data
                                <p class="category">You can see only your patients</p></h1>
                            </div>
                            <div class="row">
                                <div class="form-group" style="margin-left:10px;margin-top:10px">
                                    <div class="col-sm-2" style="width:10%">
                                        <select class="form-control" name="searchname" id="searchname">
                                            <option value="name">Name</option>
                                            <option value="email">Email</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2" style="margin-left: -20px;">
                                        <input type="text" class="form-control" id="searchtext">
                                    </div>
                                    <div class="col-sm-1">
                                        <button type="button" class="btn" onclick="patientsearch()">Search</button>
                                    </div>
                                </div>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table id="patientlist" class="table table-hover">
                                    <thead>
                                        <th>Email</th>
                                    	<th>Last Name</th>
                                    	<th>Frist Name</th>
                                    	<th>Phone</th>
                                    	<th>Gender</th>
                                        <th>Birth</th>
                                        <th>Heart</th>
                                        <th>AQI</th>
                                        <th>Connection</th>
                                    </thead>
                                </table>
                            </div>
                        </div>
                        <div class="row" style="margin-left: 7px;">
                            <h3 align="center"style="font-family: 'Lato', Arial, sans-serif">Connection State<br></h3>
                            <table id="connstate" class="table table-hover">
                                <thead>
                                <tr>
                                    <th>Connect</th>
                                    <th>Disconnect</th>
                                    <th>Acceptance</th>
                                    <th>Waiting</th>
                                </tr>
                                <tr>
                                    <td style="font-family: 'Lato', Arial, sans-serif">You can connect with patient</td>
                                    <td style="font-family: 'Lato', Arial, sans-serif">You already connected with a patient and you can disconnect with a connected patient</td>
                                    <td style="font-family: 'Lato', Arial, sans-serif">You received connection request and you can accept it</td>
                                    <td style="font-family: 'Lato', Arial, sans-serif">You requested connection with patient and now you are waiting for patient's acceptance</td>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
    var count = <?echo count($data) ?> - 1;
    $(function showtable() {
        if(<?php echo isset($data)?>) {
            var table = document.getElementById('patientlist');

            <?
            for($i=0;$i<count($data)-1;$i++) {
                $email = $data[$i]['email']; $lname = $data[$i]['lname']; $fname = $data[$i]['fname']; $phone = $data[$i]['phone'];
                $birth = $data[$i]['birth']; $gender = $data[$i]['gender']; $usn = $data[$i]['usn']; $requestingUSN = $data[$i]['requestingUSN'];
                $requestedUSN = $data[$i]['requestedUSN']; $CONN_sate = $data[$i]['CONN_state'];
                ?>
                var objRow = table.insertRow();

                var new_email = objRow.insertCell(), new_lname = objRow.insertCell(),new_fname = objRow.insertCell(), new_phone = objRow.insertCell(),
                new_gender = objRow.insertCell(), new_birth = objRow.insertCell() ,new_heartbutton = objRow.insertCell(), new_aqibutton = objRow.insertCell(), new_connection = objRow.insertCell();

                new_email.innerHTML = "<? echo $email; ?>";
                new_lname.innerHTML = "<? echo $lname; ?>";
                new_fname.innerHTML = "<? echo $fname; ?>";
                new_phone.innerHTML = "<? echo $phone; ?>";

                <?if($CONN_sate == 1) {?>

                    <?if($gender==1) {?>
                        new_gender.innerHTML = "Male";
                    <?}
                    else {?>
                        new_gender.innerHTML = "Female";
                    <?}?>
                    new_birth.innerHTML = "<? echo $birth; ?>";
                    new_connection.innerHTML = '<input type = "button" class="btn" value="Disconnect" onclick="Disconnect(document.getElementById(\'disconnbtn<?echo $i;?>\').value)"> ' +
                        '<input type="hidden" id="disconnbtn<? echo $i;?>" value="<? echo $usn;?>">';
                    new_heartbutton.innerHTML = '<input type = "button" class="btn" value="View" onclick="Heartrate(document.getElementById(\'heartbtn<?echo $i;?>\').value)"> ' +
                        '<input type="hidden" id="heartbtn<? echo $i;?>" value="<? echo $usn;?>">';
                    new_aqibutton.innerHTML = '<input type = "button" class="btn" value="View" onclick="Aqi(document.getElementById(\'aqibtn<?echo $i;?>\').value)"> ' +
                        '<input type="hidden" id="aqibtn<? echo $i;?>" value="<? echo $usn;?>">';
                    <?}
                else {?>
                    <?if($requestedUSN == $_SESSION['dsn']) {?>
                        new_connection.innerHTML = '<input type = "button" class="btn" value="Acceptance" onclick="Connecting(document.getElementById(\'connectionbtn<?echo $i;?>\').value)"> ' +
                            '<input type="hidden" id="connectionbtn<? echo $i;?>" value="<? echo $usn;?>">';
                    <?}
                    else if($requestingUSN == $_SESSION['dsn']) {?>
                        new_connection.innerHTML = '<input type = "button" class="btn" value="Waiting" onclick="Disconnect(document.getElementById(\'waitbtn<?echo $i;?>\').value)"> ' +
                            '<input type="hidden" id="waitbtn<? echo $i;?>" value="<? echo $usn;?>">';
                    <?}
                }
            }?>
        }
    });
</script>
<script>
    function Heartrate(usn) {
        var data = {
            usn: usn
        };

        $.ajax({
            type: "POST",
            url: "/patientlist",
            data: JSON.stringify(data),
            success: function (response) {

                var res = JSON.parse(response);

                if (res['status'] == true) {
                    window.location = '/realtimeheartrate';
                }
                else
                    alert(res['message']);
            }
        });
    }

    function Aqi(usn) {
        var data = {
            usn: usn
        };

        $.ajax({
            type: "POST",
            url: "/patientlist",
            data: JSON.stringify(data),
            success: function (response) {

                var res = JSON.parse(response);

                if (res['status'] == true) {
                    window.location = '/realtimeaqi';
                }
                else
                    alert(res['message']);
            }
        });
    }

    function Connecting(usn) {
        var data = {
            usn: usn,
            dsn: "<? echo $_SESSION['dsn']; ?>"
        };

        $.ajax({
            type: "POST",
            url: "/connectuser",
            data: JSON.stringify(data),
            success: function (response) {

                var res = JSON.parse(response);

                if (res['status'] == true) {
                    window.location = '/realtime';
                }
                else
                    alert(res['message']);
            }
        });
    }
    function Disconnect(usn) {
        if(confirm("Are you sure to disconnect?")) {
            var data = {
                usn: usn,
                dsn: "<? echo $_SESSION['dsn']; ?>"
            };

            $.ajax({
                type: "POST",
                url: "/disconnectuser",
                data: JSON.stringify(data),
                success: function (response) {

                    var res = JSON.parse(response);

                    if (res['status'] == true) {
                        window.location = '/realtime';
                    }
                    else
                        alert(res['message']);
                }
            });
        }
    }
</script>
<script>
    function patientsearch() {
        var target = document.getElementById('searchname');
        var data = {
            type: target.options[target.selectedIndex].text,
            value: document.getElementById('searchtext').value
        };

        $.ajax({
            type: "POST",
            url: "/patientsearch",
            data: JSON.stringify(data),
            success: function (response) {

                var res = JSON.parse(response);

                if (res['status'] == true) {
                    var table = document.getElementById('patientlist');

                    for(var i=0;i<count;i++) {
                        table.deleteRow(1);
                    }

                    count = res.data.length;

                    for(var i=0;i<count;i++) {
                        var num = res.data[i].usn;
                        var objRow = table.insertRow();
                        var new_email = objRow.insertCell(), new_lname = objRow.insertCell(),new_fname = objRow.insertCell(), new_phone = objRow.insertCell(),
                            new_gender = objRow.insertCell(), new_birth = objRow.insertCell() ,new_heartbutton = objRow.insertCell(), new_aqibutton = objRow.insertCell(), new_connection = objRow.insertCell();

                        new_email.innerHTML = res.data[i].email;
                        new_lname.innerHTML = res.data[i].lname;
                        new_fname.innerHTML = res.data[i].fname;
                        new_connection.innerHTML = '<input type = "button" value="Connect" class="btn" onclick="Conrequest(document.getElementById(\'searchbtn' + i +'\').value)">' +
                            '<input type="hidden" id="searchbtn' + i + '" value="' + res.data[i].usn + '">';
                    }
                }
                else
                    alert(res['message']);
            }
        });
    }
</script>
<script>
    function Conrequest(usn) {
        var data = {
            usn: usn
        };

        $.ajax({
            type: "POST",
            url: "/conrequest",
            data: JSON.stringify(data),
            success: function (response) {

                var res = JSON.parse(response);

                if (res['status'] == true) {
                    alert(res['message']);
                    window.location = '/realtime';
                }
                else
                    alert(res['message']);
            }
        });
    }
</script>

</body>

<!--   Core JS Files   -->
<script src="assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="assets/js/demo.js"></script>
</html>