<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>My Doctor A | Sign In Page</title>

    <!-- Bootstrap CSS -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Custom styles -->
    <link href="assets/css/style.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="login-img-body">
<div class="container" style="text-align:center">
    <br></br><br></br>
    <i class="fa fa-heartbeat" style="font-size:3em;color:white"></i>
    <br></br>
    <font color=#ffffff size=5em>Sign in to MydoctorA</font>
    <form id="signin-form" class="login-form">
        <div class="login-wrap">
            <div class="input-group">
                <span class="input-group-addon"><i class="icon_profile"></i></span>
                <input type="text" class="form-control" id="email" placeholder="E-mail" autofocus>
            </div>
            <div class="input-group">
                <span class="input-group-addon"><i class="icon_key_alt"></i></span>
                <input type="password" class="form-control" id="password" placeholder="Password">
            </div>
            <div style=align-text:justify>
                <a href="/chkemail"><font color="#a7a7a7" size=2> Create an account</font></a>
                <font size=3em>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</font>
                <a href="/forgottenmail"><font color="#a7a7a7" size=2> Forgot Password?</font></a>
                <font size=0.4><br></br></font>
            </div>
            <button class="btn btn-primary btn-lg btn-block" type="submit">Sign In</button>
        </div>
        <script type="text/javascript">
            $("#signin-form").submit(function(){
                var data = {
                    useremail: $('#email').val(),
                    userpassword: $('#password').val()
                };
                $.ajax({
                    type: "POST",
                    url: "/signin",
                    data: JSON.stringify(data),
                    success: function(response) {
                        var res = JSON.parse(response);
                        if (res['status'] == true) {
                            window.location = '/';
                        }
                        else
                            alert(res['message']);
                    }
                });
                return false;
            });
        </script>
    </form>

</body>

</html>