<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Sign in to MydoctorA</title>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Themify Icons-->
    <link rel="stylesheet" href="css/themify-icons.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="css/bootstrap.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="css/magnific-popup.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="css/bootstrap-datepicker.min.css">

    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="css/style.css">

    <!-- Modernizr JS -->
    <script src="js/modernizr-2.6.2.min.js"></script>
</head>

<body>

  <div class="login-page" style="text-align:center">
    <i class="fa fa-heartbeat" style="font-size:3em;color:white"></i>
    <br></br>
    <font color=#ffffff size=5em>Sign in to MydoctorA</font>
    <br></br>
  <div class="form">
    <form id="signin-form" class="login-form" method="post">
      <input type="text" id="email" placeholder="Email address"/>
      <input type="password" id="password" placeholder="Password"/>
      <button type="submit" onclick="datasubmit()">Sign in</button>
      <p class="message">Not registered? <a href="/signup">Create an account</a></p>

      <script>

          $("#signin-form").submit(function(){
          function datasubmit(){
              var data = {
                  useremail: document.getElementById("email").value,
                  userpassword: document.getElementById("password").value
              };

              $.ajax({
                  type: "POST",
                  url: "/signin",
                  data: JSON.stringify(data),

                  success: function(response) {

                      var res = JSON.parse(response);

                      if (res['status'] == true) {
                          window.location = '/';
                      }
                      else
                          alert(res['message']);
                  }
              });

              return false;
          }
      </script>
    </form>
  </div>
</div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="http://code.jquery.com/jquery-1.12.4.js"></script>
  <script  src="js/signIn.js"></script>




</body>

</html>
