<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="img/favicon.png">

  <title>My Doctor A | Sign In Page</title>

  <!-- Bootstrap CSS -->
  <link href="assets/css/bootstrap.min.css" rel="stylesheet">
  <!-- bootstrap theme -->
  <link href="css/bootstrap-theme.css" rel="stylesheet">
  <!--external css-->
  <!-- font icon -->
  <link href="css/elegant-icons-style.css" rel="stylesheet" />
  <link href="css/font-awesome.css" rel="stylesheet" />
  <!-- Custom styles -->
  <link href="assets/css/style.css" rel="stylesheet">
  <link href="css/style-responsive.css" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
  <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>

    <![endif]-->
</head>

<body class="login-img-body">

  <div class="container">

    <form id="signin-form" class="login-form">
      <div class="login-wrap">
        <div class="input-group">
          <span class="input-group-addon"><i class="icon_profile"></i></span>
          <input type="text" class="form-control" id="email" placeholder="E-mail" autofocus>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><i class="icon_key_alt"></i></span>
          <input type="password" class="form-control" id="password" placeholder="Password">
        </div>
        <label class="checkbox" style="margin-left:20px">
                <input type="checkbox" value="remember-me"> Remember me
                <span class="pull-right"> <a href="/forgottenmail"> Forgot Password?</a></span>
        </label>
        <button class="btn btn-primary btn-lg btn-block" type="submit">Sign In</button>
      </div>
        <script type="text/javascript">
          $("#signin-form").submit(function(){
              var data = {
                  useremail: $('#email').val(),
                  userpassword: $('#password').val()
              };

              $.ajax({
                  type: "POST",
                  url: "/signin",
                  data: JSON.stringify(data),

                  success: function(response) {

                      var res = JSON.parse(response);

                      if (res['status'] == true) {
                          window.location = '/';
                      }
                      else
                          alert(res['message']);
                  }
              });

              return false;
          });
        </script>
    </form>

</body>

</html>