<?php require('common/head.php') ?>
<?php require('common/body.php')?>

        <div class="content">
            <div class="container-fluid">
                <div class="col-md-6">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Sign Up</h4>
                        </div>
                        <div class="content">
                            <form id="signup-form" method="post" class="form-group">
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Email address</label>
                                            <input type="text" id="inputemail" class="form-control" placeholder="Email" value="<? echo $_SESSION['email']?>" required disabled>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>License information</label>
                                            <input type="text" id="inputnpi" placeholder="NPI" class="form-control">
                                            <br>
                                            <input type="text" id="inputlicense" placeholder="license number" class="form-control">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" id="inputpwd" class="form-control" placeholder="password" pattern="[A-Za-z0-9]{7,16}" maxlength="16" required>
                                            <br>
                                            <input type="password" id="inputcpwd" class="form-control" placeholder="confirm Password"pattern="[A-Za-z0-9]{7,16}" maxlength="16" required><br>
                                            <div style="text-align:rignt">
                                              <font color =#787878 size=1px>
                                                Password must be Minimum of 7 characters in length and have at least one numerical digit and character
                                              </font>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Name</label>
                                            <input type="text" id="inputfname" class="form-control" placeholder="first name" required>
                                            <br>
                                            <input type="text" id="inputlname" class="form-control" placeholder="last name" required>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-10">
                                        <label>Gender</label>
                                        <div class="form-group" name="radio_name" style="margin:10px">
                                            <div class="radio-inline">
                                                <label>
                                                <input type="radio" name="gender" value="1" checked>Male</label>
                                            </div>
                                            <div class="radio-inline">
                                                <label>
                                                <input type="radio" name="gender" value="0">Female</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Birth</label>
                                            <div class="input-group date">
                                                <div class="input-group-addon">
                                                    <i class="fa fa-calendar"></i>
                                                </div>
                                                <input type="date" class="form-control pull-right" id="inputbirth" value="1980-01-01">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                  <label class="col-lg-10">Phone</label>
                                    <div class="form-group">
                                        <div class="col-md-3">
                                            <input type="text" id="inputfnum" class="form-control" maxlength="3" required>
                                        </div>
                                        <div class="col-sm-1" style="padding:10px;margin-right:-10px" > -</div>
                                        <div class="col-md-3">
                                            <input type="text" id="inputmnum" class="form-control" maxlength="3" required>
                                        </div>
                                        <div class="col-sm-1" style="padding:10px;margin-right:-10px"> -</div>
                                        <div class="col-md-3">
                                            <input type="text" id="inputlnum" class="form-control" maxlength="4" required>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-info btn-fill pull-left">SUBMIT</button>
                                <div class="clearfix"></div>

                                <script type="text/javascript">
                                    $("#signup-form").submit(function(){
                                        var pd1 = $("#inputpwd").val();
                                        var pd2 = $("#inputcpwd").val();
                                        var charcount = 0;
                                        var numcount = 0;

                                        if(pd1!=pd2) {
                                            alert("Password is not matched");
                                            return false;
                                        }

                                        for(var i = 0; i < pd1.length; i++) {
                                            if(pd1[i]>="A" && pd1[i]<='z') {
                                                charcount++;
                                            }
                                            if(pd1[i]>=0 && pd1[i]<=9) {
                                                numcount++;
                                            }
                                        }

                                        if(charcount<2 || numcount<1) {
                                            alert("You must contain at least two characters and a number");
                                            return false;
                                        }

                                        for(var i = 0; i < 2; i++) {
                                            if(document.getElementsByName("gender")[i].checked) {
                                                var gender = document.getElementsByName("gender")[i].value;
                                                break;
                                            }
                                        }

                                        var arr = [$("#inputfnum").val(),$("#inputmnum").val(),$("#inputlnum").val()];
                                        var phone =  arr.join("-");

                                        var data = {
                                            email : $("#inputemail").val(),
                                            pwd : $("#inputpwd").val(),
                                            birth : $("#inputbirth").val(),
                                            fname : $("#inputfname").val(),
                                            lname : $("#inputlname").val(),
                                            phone : phone,
                                            gender : gender,
                                            npicode: $("#inputnpi").val(),
                                            license: $("#inputlicense").val()
                                        };

                                        $.ajax({
                                            type: "POST",
                                            url: "/signup",
                                            data: JSON.stringify(data),

                                            success: function (response) {

                                                var res = JSON.parse(response);

                                                if (res['status'] === true) {
                                                    window.location = '/successmessage';
                                                }
                                                else
                                                    alert(res['message']);
                                            }
                                        });
                                        return false;
                                    });
                                </script>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


</body>
</html>
