<?php require('common/head.php')?>
<?php require('common/body.php')?>

        <div class="content">
            <div class="container-fluid">
                <div class="col-md-4">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Verification Code</h4>
                        </div>
                        <div class="content">
                            <form id="chkcode-form" method="post" class="form-group">
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Verification Code</label>
                                            <input type="text" id="chkcode" class="form-control" placeholder="Input Verificaiton Code" maxlength="12">
                                            <!--<div id="timer_board" class="pull-right" style="margin-top:5px;font-size:25px"></div>-->
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-info btn-fill pull-left" id="timer_board">SUBMIT</button>
                                <div class="clearfix"></div>

                                <script type="text/javascript">
                                    <? if(!(isset($_SESSION['code'])))
                                    {?>
                                        window.location='/';
                                    <?}
                                    else {?>
                                        var myTimer=function(set_number){
                                            var my_timer =function(){
                                                if(set_number==0){
                                                    alert("Time Out");
                                                    window.location = '/';
                                                }
                                                else{
                                                    var mm = Math.floor(set_number / 60); var ss = String("0" + set_number % 60).slice(-2);
                                                    document.getElementById("timer_board").innerHTML = mm + ":" + ss;
                                                    set_number--;
                                                }
                                            };
                                            var my_set=setInterval(my_timer, 1000)
                                        }

                                        myTimer(180);

                                        $("#chkcode-form").submit(function(){

                                            if ('<?php echo $_SESSION['code'] ?>' == document.getElementById('chkcode').value) {
                                                if ('<?php echo $_SESSION['codenum']?>' == 0)
                                                    window.location = '/fchangepwd';
                                                else if ('<?php echo $_SESSION['codenum']?>' == 1) {
                                                    <? unset($_SESSION['code']);?>
                                                    window.location = '/signup';
                                                }
                                            }
                                            else {
                                                alert("code is wrong");
                                            }

                                            return false;

                                        });
                                    <?}?>
                                </script>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- jQuery 3 -->
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Select2 -->
<script src="bower_components/select2/dist/js/select2.full.min.js"></script>
<!-- InputMask -->
<script src="plugins/input-mask/jquery.inputmask.js"></script>
<script src="plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="plugins/input-mask/jquery.inputmask.extensions.js"></script>
<!-- date-range-picker -->
<script src="bower_components/moment/min/moment.min.js"></script>
<script src="bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- bootstrap datepicker -->
<script src="bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- bootstrap color picker -->
<script src="bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
<!-- bootstrap time picker -->
<script src="plugins/timepicker/bootstrap-timepicker.min.js"></script>
<!-- SlimScroll -->
<script src="bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- iCheck 1.0.1 -->
<script src="plugins/iCheck/icheck.min.js"></script>
<!-- FastClick -->
<script src="bower_components/fastclick/lib/fastclick.js"></script>

</body>

    <!--   Core JS Files   -->
    <script src="assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="assets/js/bootstrap-notify.js"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="assets/js/demo.js"></script>

</html>
